# Generated by Django 5.1.7 on 2025-03-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('colaborador', 'criterio')},
        ),
    ]
