# Generated by Django 5.1.7 on 2025-03-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_criterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.criterio'),
        ),
    ]
