# Generated by Django 5.1.7 on 2025-03-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_avaliacao_criterio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador'},
        ),
    ]
